# This is a basic workflow to help you get started with Actions
# Github Action Workflow Name
name: nodejs installer
# When to run the workflow - make it manually triggerable
on: workflow_dispatch

# Steps to run
jobs:
  # Job Name : installation
  installation:
    # Runner - Where to run the job
    runs-on: ubuntu-latest
    # Steps to run - to do job (installation)
    steps:
      # step 1 - Checkout the code
      - name: Checkout # name of the step
        uses: actions/checkout@v3
      # step 2 - Install NodeJS and npm
      - name: Install NodeJS # name of the step
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
      # step 3 - Verify the installation
      - name: Verify Installation # name of the step
        run: |
          node --version
          npm --version
  
  # Job Name : verification
  verification:
    # Runner - Where to run the job
    runs-on: ubuntu-latest
    # Dependencies - what jobs to run before this job
    needs: installation
    # Steps to run - to do job (verification)
    steps:
      # step 1 - Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # step 2 - Setup NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      # step 3 - install dependencies
      - name: Install dependencies
        run: npm install

      # step 4 - build the application
      - name: Build the application
        run: npm run build
      


